export const data= [
    {
        id:Math.random(),
        price:10,
        order:"one",
    }
    ,
    {
        id:Math.random(),
        price:20,
        order:"two",
    }
    ,
    {
        id:Math.random(),
        price:30,
        order:"three",
    }
    ,
    {
        id:Math.random(),
        price:40,
        order:"four",
    }
    ,
    {
        id:Math.random(),
        price:50,
        order:"five",
    }
    ,
    {
        id:Math.random(),
        price:60,
        order:"six",
    }
    ,
    {
        id:Math.random(),
        price:70,
        order:"seven",
    }
    ,
    {
        id:Math.random(),
        price:80,
        order:"eight",
    }
    ,
    {
        id:Math.random(),
        price:90,
        order:"nine",
    }
    ,
    {
        id:Math.random(),
        price:100,
        order:"ten",
    }
    ,

]